site_name: WebprofesNSC
site_description: Recursos de IA para docentes
site_author: Superagente IA

theme:
  name: material
  language: es
  logo: logoletras.png  # <--- ESTA ES LA LÍNEA NUEVA
  favicon: logoletras.png # <--- Añade esta también para que salga el icono en la pestaña del navegador
palette:
  scheme: default
  primary: indigo
  accent: purple

nav:
 - Inicio: index.md
 - Herramientas:
      - 'Herramientas IA': herramientas-ia.md
      - 'Herramientas Aula': herramientas-aula.md
  - Ecosistema Google: google-ia.md
  - Biblioteca de Prompts:
      - 'Evaluación': prompts/evaluacion.md
      - 'Actividades': prompts/ActividadesAula.md
