site_name: WebprofesNSC
site_description: Recursos de IA para docentes
site_author: Superagente IA

theme:
  name: material
  language: es
  logo: letras.png  # <--- ESTA ES LA LÍNEA NUEVA
  favicon: letras.png # <--- Añade esta también para que salga el icono en la pestaña del navegador
palette:
  scheme: default
  primary: indigo
  accent: purple

nav:
  - Inicio: index.md
  - Herramientas: herramientas.md
  - Ecosistema Google: google-ia.md
  - Biblioteca de Prompts:
      - 'Evaluación': prompts/evaluacion.md
